"""Regenerate js/campus-data.js from tools/campus.osm.

Download a fresh extract with:
  curl -A "uom-campus-map" -o tools/campus.osm \
    "https://api.openstreetmap.org/api/0.6/map?bbox=79.8975,6.7930,79.9045,6.7995"
then run:  python tools/build_campus_data.py
"""
import json
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tools", "campus.osm")
OUT = os.path.join(ROOT, "js", "campus-data.js")

# Rough box around the campus; roads outside it are dropped.
LAT_MIN, LAT_MAX, LON_MIN, LON_MAX = 6.7940, 6.8002, 79.8975, 79.9040
WALKABLE = {"service", "unclassified", "footway", "steps", "path", "pedestrian",
            "living_street", "residential", "tertiary", "primary", "secondary"}
CAMPUS_WAY = "272552647"

root = ET.parse(SRC).getroot()
nodes = {n.get("id"): (round(float(n.get("lat")), 6), round(float(n.get("lon")), 6))
         for n in root.iter("node")}
tags = lambda e: {t.get("k"): t.get("v") for t in e.findall("tag")}
inside = lambda p: LAT_MIN <= p[0] <= LAT_MAX and LON_MIN <= p[1] <= LON_MAX

# Buildings mapped as multipolygons carry their tags on the relation (e.g. Sumanadasa).
outer_of_building = {m.get("ref") for r in root.iter("relation") if "building" in tags(r)
                     for m in r.findall("member") if m.get("type") == "way" and m.get("role") == "outer"}

buildings, roads, campus = {}, [], None
for w in root.iter("way"):
    t = tags(w)
    if w.get("id") in outer_of_building:
        t.setdefault("building", "yes")
    pts = [nodes[nd.get("ref")] for nd in w.findall("nd") if nd.get("ref") in nodes]
    if len(pts) < 2:
        continue
    if w.get("id") == CAMPUS_WAY:
        campus = pts
    elif "building" in t and any(inside(p) for p in pts):
        buildings[w.get("id")] = pts
    elif t.get("highway") in WALKABLE:
        # Keep only the stretches that are inside the campus box.
        run = []
        for p in pts:
            if inside(p):
                run.append(p)
            else:
                if len(run) > 1:
                    roads.append(run)
                run = []
        if len(run) > 1:
            roads.append(run)

def in_poly(pt, poly):
    x, y, hit = pt[1], pt[0], False
    for (ay, ax), (by, bx) in zip(poly, poly[1:] + poly[:1]):
        if (ay > y) != (by > y) and x < (bx - ax) * (y - ay) / (by - ay) + ax:
            hit = not hit
    return hit

# Only keep footprints whose centre is on campus (the base map shows the rest).
if campus:
    buildings = {k: v for k, v in buildings.items()
                 if in_poly((sum(p[0] for p in v) / len(v), sum(p[1] for p in v) / len(v)), campus)}

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Generated by tools/build_campus_data.py from OpenStreetMap data.\n")
    f.write("// (c) OpenStreetMap contributors, ODbL. Do not edit by hand.\n")
    f.write("window.CAMPUS_DATA = ")
    json.dump({"campus": campus, "buildings": buildings, "roads": roads}, f, separators=(",", ":"))
    f.write(";\n")
print(f"wrote {OUT}: {len(buildings)} buildings, {len(roads)} road segments")
